solace:
  default-site-no: ${NODE.SITE.NO}
  vpn-id: ${SOLACE_VPN_UNIQUE_ID:1}
  nodes:
    - host: ${SOLACE_HOST:tcp://mr17km0la8m7d.messaging.solace.cloud:55555}
      msgVpn: ${SOLACE_MSG_VPN:hyperservicex}
      clientUsername: ${SOLACE_CLIENT_USERNAME:solace-cloud-client}
      clientPassword: ${SOLACE_CLIENT_PASSWORD:3kuoanopc134pii7u8ltbrbpud}
      apiProperties:
        allow-guaranteed‑message‑receive: true
        allow‑guaranteed‑endpont-create: true
        IGNORE_DUPLICATE_SUBSCRIPTION_ERROR: true
  topics:
    templates:
      v1:
        SA_STATUS: HSX0${NODE.SITE.NO}/${solace.vpn-id}/G/ADM/SASTATUS/$[operation]/NFY/SA0${NODE.NO}/$[messageEntryPoint]/V1/JSON
